SELECT COUNT(EMPLOYEE_ID), JOB_ID
FROM employees
GROUP BY JOB_ID;


SELECT MANAGER_ID, LAST_NAME
FROM employees
GROUP BY MANAGER_ID
ORDER BY MIN(SALARY);


SELECT DEPARTMENT_ID, SUM(SALARY)
FROM employees
GROUP BY DEPARTMENT_ID;


SELECT JOB_ID, AVG(SALARY)
FROM employees
WHERE JOB_ID NOT LIKE '[IT_PROG]%'
GROUP BY JOB_ID;


SELECT JOB_ID, SALARY
FROM employees
GROUP BY JOB_ID
HAVING MAX(SALARY) >= 4000;


SELECT AVG(SALARY), DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
FROM employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) > 10;