SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY BETWEEN 10000 AND 15000
AND DEPARTMENT_ID IN('30', '100');


SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM employees
WHERE YEAR(HIRE_DATE)=1987;


SELECT FIRST_NAME
FROM employees
WHERE FIRST_NAME LIKE'%b%' AND FIRST_NAME LIKE'%c%';


SELECT LAST_NAME, JOB_ID, SALARY
FROM employees
WHERE JOB_ID IN('IT_PROG', 'SH_CLERK') AND
SALARY <> 4500 AND 10000 AND 15000;


SELECT * 
FROM employees
WHERE (LAST_NAME) IN('BLAKE', 'SCOTT', 'KING', 'FORD');